# Generated by Django 2.2.24 on 2021-08-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/avatar1.png', upload_to='images/avatar/'),
        ),
    ]
