# Generated by Django 2.2.24 on 2021-08-13 09:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='名前')),
                ('rank', models.CharField(max_length=10, verbose_name='繰り返しランク')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='original/', verbose_name='加工前画像')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 8, 13, 9, 12, 55, 570734, tzinfo=utc), verbose_name='日付')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photoremake.User', verbose_name='ユーザー')),
            ],
        ),
    ]
