# Generated by Django 2.2.24 on 2021-08-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoremake', '0002_auto_20210813_1814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Photo',
        ),
    ]
