# Generated by Django 2.2.24 on 2021-08-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoremake', '0004_auto_20210813_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='original', verbose_name='加工前画像'),
        ),
    ]
