# Generated by Django 2.2.24 on 2021-08-14 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoremake', '0007_auto_20210813_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Back',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='背景タイトル')),
                ('back_img', models.ImageField(blank=True, default='タイトル', null=True, upload_to='images/back/', verbose_name='背景画像')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinated',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='タイトル', max_length=50, verbose_name='タイトル')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/coordinated/', verbose_name='加工後画像')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
                ('back_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photoremake.Back', verbose_name='背景画像')),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/original/', verbose_name='加工前画像'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='coordinated',
            name='photo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photoremake.Photo', verbose_name='加工前画像'),
        ),
    ]
