# Generated by Django 2.2.24 on 2021-08-13 15:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photoremake', '0007_auto_20210813_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinated',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='加工後画像')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
                ('photo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photoremake.Photo', verbose_name='加工前画像')),
            ],
        ),
    ]
