# Generated by Django 2.2.24 on 2021-08-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoremake', '0008_auto_20210814_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinated',
            name='back_id',
        ),
        migrations.RemoveField(
            model_name='coordinated',
            name='photo_id',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='date',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='photo',
            name='output',
            field=models.ImageField(default='output/output.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='defo', upload_to='images/original/'),
        ),
        migrations.DeleteModel(
            name='Back',
        ),
        migrations.DeleteModel(
            name='Coordinated',
        ),
    ]
