# Generated by Django 2.2.24 on 2021-08-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoremake', '0008_coordinated'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinated',
            name='title',
            field=models.CharField(default='タイトル', max_length=50, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='coordinated',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/coordinated/', verbose_name='加工後画像'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/original/', verbose_name='加工前画像'),
        ),
        migrations.CreateModel(
            name='Back',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='背景タイトル')),
                ('back_img', models.ImageField(blank=True, default='タイトル', null=True, upload_to='images/back/', verbose_name='背景画像')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photoremake.User', verbose_name='ユーザー')),
            ],
        ),
        migrations.AddField(
            model_name='coordinated',
            name='back_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photoremake.Back', verbose_name='背景画像'),
        ),
    ]
