# Generated by Django 2.2.24 on 2021-08-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoremake', '0008_auto_20210814_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinated',
            name='colorChangedImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/colorChanged/', verbose_name='色加工後画像'),
        ),
    ]
