# Generated by Django 2.2.24 on 2021-08-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoremake', '0009_auto_20210814_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='defo', upload_to='original/'),
        ),
    ]
