# Generated by Django 2.2.24 on 2021-08-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoremake', '0009_coordinated_colorchangedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinated',
            name='colorChangedImage',
        ),
        migrations.AddField(
            model_name='photo',
            name='colorChangedImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/colorChanged/', verbose_name='色加工後画像'),
        ),
    ]
