# Generated by Django 2.2.24 on 2021-08-14 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoremake', '0010_auto_20210814_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='colorChangedImage',
        ),
    ]
