# Generated by Django 2.2.24 on 2021-08-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoremake', '0011_remove_photo_colorchangedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('photo', models.ImageField(default='default', upload_to='images/photo/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('output', models.ImageField(default='output/output.jpg', upload_to='')),
            ],
        ),
    ]
