# Generated by Django 2.2.24 on 2021-08-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoremake', '0013_auto_20210814_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='no title', max_length=20),
        ),
    ]
