# Generated by Django 2.2.24 on 2021-08-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoremake', '0012_auto_20210815_0012'),
        ('photoremake', '0013_auto_20210815_0419'),
    ]

    operations = [
    ]
