# Generated by Django 2.2.24 on 2021-08-14 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoremake', '0015_auto_20210815_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='profiles.Profile'),
        ),
    ]
