# Generated by Django 2.2.24 on 2021-08-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoremake', '0015_post'),
        ('photoremake', '0010_auto_20210814_1521'),
    ]

    operations = [
    ]
