# Generated by Django 2.2.24 on 2021-08-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoremake', '0016_auto_20210815_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='author',
        ),
    ]
